# permissions for end users to view frigates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: frigate-viewer-role
rules:
- apiGroups:
  - ship.example.org
  resources:
  - frigates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ship.example.org
  resources:
  - frigates/status
  verbs:
  - get
