---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ship.example.org
  resources:
  - frigates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ship.example.org
  resources:
  - frigates/finalizers
  verbs:
  - update
- apiGroups:
  - ship.example.org
  resources:
  - frigates/status
  verbs:
  - get
  - patch
  - update
