apiVersion: ship.example.org/v1beta1
kind: Frigate
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: frigate-sample
spec:
  # TODO(user): Add fields here
  action: hello
  object: world
